{
 "title": "Exa project",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Index data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number prefixes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "redis_model_count{model=\"URLPrefix\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number URLs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "redis_model_count{model=\"URL\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "title": "Queue data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "URL prefixes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "redis_queue_length{model=\"URLPrefix\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URLs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "redis_queue_length{model=\"URLQueueItem\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Number of evaluation runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "redis_model_count{model=\"EvaluationRun\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}